### ISSUE TITLE
Can't clone use without logged into github

### ISSUE THREAD

**Issue by hmic** [embeddedartistry/arduino-printf#15]
You specify the submodules with git@github.com URLs, which makes it necessary to be logged into github to clone them.

If you specify them as https://github.com/... they can just be used as is.

**Comment by phillipjohnston** [comment]
It's a habit from years of using private repositories, which require you to have SSH keys configured. I'm happy to make the fix, although I see here that you have a commit which addresses the issue. Did you want to submit it as a PR? I will gladly accept it.

**Comment by phillipjohnston** [comment]
Just found out I can open a PR using your fork - I'll get this merged today.

**Comment by phillipjohnston** [comment]
Closed by PR #16
