### ISSUE TITLE
Does this library include a sprintf() or snprintf() implementation?

### ISSUE THREAD

**Issue by scottchiefbaker** [embeddedartistry/arduino-printf#2]
This may be a documentation related question...

Does arduino-printf include a `sprintf()` or `snprintf()` implementation?

**Comment by phillipjohnston** [comment]
Yes, `s[n]printf` as well as `v[sn]printf` if you need to use it with varargs. Will add that to README as well.

https://github.com/embeddedartistry/arduino-printf/blob/master/src/printf.h

**Comment by scottchiefbaker** [comment]
Excellent... thank you!
