### ISSUE TITLE
Hex # flag not printed for zero value

### ISSUE THREAD

**Issue by robdunn4** [embeddedartistry/arduino-printf#32]
printf() does not print leading "0x" with # flag for a zero value parameter.

Code sample:

  printf("%#X %#X %#X\n", 0xffff, 0xa5, 0x0000);
  printf("%#4.4X %#4.4X %#4.4X\n", 0xffff, 0xa5, 0x0000);

Results:

0XFFFF 0XA5 0                  // expected 0XFFFF 0XA5 0X0
0XFFFF 0X00A5 0000        // expected 0XFFFF 0X00A5 0X0000

**Comment by phillipjohnston** [comment]
That is the correct behavior. 

[cppreference](https://en.cppreference.com/w/cpp/io/c/fprintf):

 >In the alternative implementation 0x or 0X is prefixed to results **if the converted value is nonzero.**

[cplusplus.com](https://www.cplusplus.com/reference/cstdio/printf/):

> Used with o, x or X specifiers the value is preceeded with 0, 0x or 0X respectively **for values different than zero.**

[Microsoft docs:](https://docs.microsoft.com/en-us/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=msvc-170)

> When it's used with the o, x, or X format, the # flag uses 0, 0x, or 0X, respectively, **to prefix any nonzero output value.**

**Comment by robdunn4** [comment]
Sorry I didn't spot that.  Thanks.

**Comment by phillipjohnston** [comment]
Easy to miss. I use the pattern "0x%x" by default bc of that.
