### ISSUE TITLE
what is the macro to disable all prints 

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [embeddedartistry/arduino-printf#33]
Is there any macro where I could diable all prints, and basically fully remove the lib, when I am not debugging

**Comment by phillipjohnston** [comment]
Not at present. What I have done in the past is to make an internal print macro, such as `debug_print`. If a definition is present, such as `DISABLE_DEBUG_PRINTS`, it is defined to an empty value, otherwise it simply aliases `printf`.

I'll work on implementing something like that in the Arduino library wrapper next week.

**Comment by phillipjohnston** [comment]
Alternatively, our logging library already supports this behavior (as well as configurable log levels): https://github.com/embeddedartistry/arduino-logger

**Comment by oneandonlyonebutyou** [comment]
> Not at present. What I have done in the past is to make an internal print macro, such as `debug_print`. If a definition is present, such as `DISABLE_DEBUG_PRINTS`, it is defined to an empty value, otherwise it simply aliases `printf`.
> 
> 
> 
> I'll work on implementing something like that in the Arduino library wrapper next week.

Thank you..: 
I am not such an expert on macros
How does your macro looks like to be able to print multiple values

**Comment by phillipjohnston** [comment]
General form:

```
#ifdef DISABLE_DEBUG_PRINT
#define debug_print(...)
#else
#define debug_print(...) printf(__VA_ARGS__)
#endif
```

**Comment by phillipjohnston** [comment]
Whoops, corrected `printf(...)` to `printf(__VA_ARGS__)`

**Comment by oneandonlyonebutyou** [comment]
Thank you .. :)

**Comment by phillipjohnston** [comment]
Sometimes i do this on a per-file basis for fine grained control. For application wide control i would make a new header like debug_print.h. In that you could include the printf header. Your source files will include the debug_printf.h header

Cheers,

Phillip
