### ISSUE TITLE
How to print a String 

### ISSUE THREAD

**Issue by oneandonlyonebutyou** [embeddedartistry/arduino-printf#34]
I have a 
```
String  s = "Hello" 
```
Serial.print(s); // works 
printf("%s\n",s). << Does not work :(

**Comment by phillipjohnston** [comment]
Sorry - I responded to you via email but it appears it did not post here.

`printf` only works with C strings (it is a C language function, not C++). If you have a String object, you can access that via the `c_str` member function:

```
printf("%s\n", s.c_str());
```
